name: Build electron app
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: cat ./package.json
      - uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
