name: Build Electron App
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'version bump to')"
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          git config --global user.name "${{ secrets.NAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
      - run: npm version patch -m 'ci:&nbsp;version bump to %s'
      - run: git push --follow-tags origin main
        env:
          GH_PAT: ${{ secrets.TOKEN }}
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
