name: Build Electron App
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          git config --global user.name "${{ secrets.NAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
      - run: npm version patch -m "Bump version to %s [skip ci]"
      - run: npm version patch -m "Bump version to %s [skip ci]"
      - run: git push --follow-tags
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
